import { StackManager } from '../components/StackManager.js';

export class Character extends Phaser.GameObjects.Container {
    constructor(scene, x, y, textureKey) {
        super(scene, x, y);

        // We assume the textures 'body_player' and 'leg_player' were generated by Factory
        this.leftLeg = scene.add.sprite(-6, 14, `leg_${textureKey}`).setOrigin(0.5, 0.5);
        this.rightLeg = scene.add.sprite(6, 14, `leg_${textureKey}`).setOrigin(0.5, 0.5);
        this.bodySprite = scene.add.sprite(0, 0, `body_${textureKey}`).setOrigin(0.5, 0.5);

        this.add([this.leftLeg, this.rightLeg, this.bodySprite]);

        scene.add.existing(this);
        scene.physics.add.existing(this);
        this.body.setSize(32, 32);
        this.body.setCollideWorldBounds(true);

        this.animSpeed = 0.02;

    }

    animateWalking(isMoving, time) {
        const baseLegY = 14;
        if (isMoving) {
            const strideLength = 6;
            this.leftLeg.y = baseLegY + (Math.sin(time * this.animSpeed) * strideLength);
            this.rightLeg.y = baseLegY + (Math.sin(time * this.animSpeed + Math.PI) * strideLength);
            this.bodySprite.setScale(1 - (Math.sin(time * this.animSpeed * 2) * 0.05), 1);
        } else {
            this.leftLeg.y = baseLegY;
            this.rightLeg.y = baseLegY;
            this.bodySprite.setScale(1, 1);
        }
    }
}